import torch
import sympy as sp
from config import CONSTANTS

class Evaluator:
    def __init__(self, var_names=['x0'], device='cpu'):
        """
        Args:
            var_names (list): List of variable names, e.g., ['x0', 'x1'].
            device (str): 'cpu' or 'cuda' for GPU acceleration.
        """
        self.var_names = var_names
        self.symbols = [sp.Symbol(var) for var in var_names]
        self.device = device

    def tokens_to_function(self, tokens):
        """
        Converts the list of tokens into an optimized PyTorch function.
        Dynamically loads physical constants from config.py.
        """
        expr_str = "".join(tokens)
        
        try:
            sympy_expr = sp.parse_expr(expr_str, evaluate=False)
            
            # Base PyTorch mapping for mathematical functions
            torch_mapping = {
                "sin": torch.sin,
                "cos": torch.cos,
                "tan": torch.tan,
                "exp": torch.exp,
                "log": torch.log,
                "sqrt": torch.sqrt,
                "abs": torch.abs,
                "Abs": torch.abs,
                "sign": torch.sign,
            }
            
            # Dynamically inject constants from config.py as PyTorch tensors
            for const_name, const_value in CONSTANTS.items():
                torch_mapping[const_name] = torch.tensor(const_value, device=self.device)
            
            # We pass the custom mapping and the actual 'torch' module object
            torch_func = sp.lambdify(self.symbols, sympy_expr, modules=[torch_mapping, torch])
            return torch_func
            
        except Exception as e:
            # print(f"Conversion error in tokens_to_function: {e}")
            return None

    def calculate_nmse(self, y_true, y_pred):
        """
        Calculates the Normalized Mean Squared Error directly on PyTorch tensors.
        """
        # Safety check: if the function returned a simple float instead of a tensor
        if not isinstance(y_pred, torch.Tensor):
            y_pred = torch.full_like(y_true, fill_value=float(y_pred))
            
        # Safety check: prevent NaNs or infinite values from breaking the training
        if not torch.isfinite(y_pred).all():
            return torch.tensor(1.0, device=self.device)
            
        mse = torch.mean((y_true - y_pred)**2)
        var_true = torch.var(y_true, unbiased=False)
        
        if var_true == 0:
            return mse 
            
        return mse / var_true

    def evaluate_episode(self, tokens, X_batch, y_true):
        """
        Evaluates a single episode generated by the agent.
        X_batch and y_true must be PyTorch tensors.
        """
        func = self.tokens_to_function(tokens)
        complexity = len(tokens)
        
        # 1. Syntax penalty: The equation is unreadable
        if func is None:
            return {
                "is_valid": False,
                "nmse": torch.tensor(1.0, device=self.device),
                "complexity": complexity
            }
            
        # 2. The equation is valid, compute predictions
        try:
            # X_batch is a tensor of shape (batch_size, num_vars)
            # Unpack columns to pass them as arguments to the function
            args = [X_batch[:, i] for i in range(X_batch.shape[1])]
            y_pred = func(*args)
            
            nmse = self.calculate_nmse(y_true, y_pred)
            
            # Clip the maximum value to 1.0 to prevent gradient explosion in the RL agent
            nmse = torch.clamp(nmse, max=1.0)
            
            return {
                "is_valid": True,
                "nmse": nmse,
                "complexity": complexity
            }
            
        except Exception as e:
            # print(f"Execution error in evaluate_episode: {e}")
            return {
                "is_valid": False,
                "nmse": torch.tensor(1.0, device=self.device),
                "complexity": complexity
            }
            

            